window.hackList = [
  { id: "skip_tutorial", label: "Skip Tutorial", enabled: true },
  { id: "unlock_all_pets", label: "Unlock All Pets", enabled: false },
  { id: "infinite_gold", label: "Infinite Gold", enabled: false },
  { id: "max_level", label: "Level 100", enabled: false },
  { id: "unlock_all_items", label: "Unlock All Items", enabled: false },
  { id: "instant_epic_attacks", label: "All Epics Unlocked", enabled: false },
  { id: "teleport_menu", label: "Enable Teleport Menu", enabled: false },
  { id: "no_enemy_encounters", label: "Disable Enemy Encounters", enabled: false },
  { id: "auto_win_battles", label: "Auto-Win Battles", enabled: false },
  { id: "free_membership", label: "Fake Membership Badge", enabled: false },
  { id: "instant_kill", label: "Instant Battle Kill", enabled: false },
  { id: "click_teleporter", label: "Click Teleporter", enabled: false },

  // Additional hacks
  { id: "god_mode", label: "God Mode (No Damage)", enabled: false },
  { id: "walk_through_walls", label: "Walk Through Walls", enabled: false },
  { id: "spawn_any_pet", label: "Spawn Any Pet", enabled: false },
  { id: "unlock_all_zones", label: "Unlock All Zones", enabled: false },
  { id: "add_9999_gold", label: "Add 9999 Gold", enabled: false },
  { id: "fast_level_up", label: "Fast Level Up", enabled: false },
  { id: "infinite_mana", label: "Infinite Mana", enabled: false },
  { id: "skip_all_dialogues", label: "Skip All Dialogues", enabled: false },
  { id: "auto_collect_items", label: "Auto Collect Items", enabled: false },
  { id: "unlock_secret_areas", label: "Unlock Secret Areas", enabled: false },
  { id: "mega_jump", label: "Mega Jump (Jump Higher)", enabled: false },
  { id: "fly_mode", label: "Fly Mode", enabled: false },
  { id: "anti_ban", label: "Anti-Ban Protection", enabled: false },
  { id: "custom_avatar", label: "Custom Avatar Editor", enabled: false },
  { id: "auto_answer", label: "Auto Answer Questions", enabled: false },
  { id: "fake_teacher_mode", label: "Fake Teacher Mode", enabled: false },
  { id: "max_stars", label: "Max Star Points", enabled: false },
  { id: "ghost_mode", label: "Ghost Mode (Invisible)", enabled: false },
  { id: "speed_boost", label: "Speed Boost", enabled: false },
  { id: "change_background", label: "Change Background Scene", enabled: false },
  { id: "unlock_all_titles", label: "Unlock All Titles", enabled: false },
  { id: "unlock_all_styles", label: "Unlock All Styles", enabled: false },

  // Prodigy X featured hacks
  { id: "battle_editor", label: "Battle Modifier (Prodigy X)", enabled: false },
  { id: "custom_damage", label: "Custom Damage Output (Prodigy X)", enabled: false },
  { id: "equip_any_item", label: "Equip Any Item (Prodigy X)", enabled: false },
  { id: "set_battle_team", label: "Custom Battle Team", enabled: false },
  { id: "manipulate_inventory", label: "Inventory Editor", enabled: false },
  { id: "set_pet_stats", label: "Set Pet Stats (HP, Level)", enabled: false },
  { id: "fake_arena_rank", label: "Fake Arena Rank Badge", enabled: false },
  { id: "unlock_epic_attacks", label: "Unlock All Epic Attacks", enabled: false },
  { id: "open_shop_menu", label: "Force Shop Open Anywhere", enabled: false },
  { id: "place_items_anywhere", label: "Place Items Anywhere (Decor Mode)", enabled: false },
  { id: "custom_question_difficulty", label: "Change Question Difficulty", enabled: false },

  // Flex & Utility Hacks
  { id: "infinite_food", label: "Infinite Food", enabled: false },
  { id: "max_currency", label: "Max Every Currency", enabled: false },
  { id: "rare_items_only", label: "All Rare Items Only", enabled: false },
  { id: "max_spin_wheel", label: "Max Rewards From Wheel Spin", enabled: false },
  { id: "open_ultimate_chest", label: "Open Ultimate Chest (Anytime)", enabled: false },
  { id: "infinite_time", label: "Infinite Time in Minigames", enabled: false },
  { id: "custom_game_guide", label: "Custom Prodigy Game Guide", enabled: false },
  { id: "glow_effects", label: "Enable Glow Effects", enabled: false },
  { id: "golden_name_tag", label: "Golden Name Tag", enabled: false },
  { id: "create_custom_pet", label: "Create Your Own Pet", enabled: false },
  { id: "level_all_pets", label: "Level Up All Pets Instantly", enabled: false },
  { id: "infinite_spin_tokens", label: "Infinite Spin Tokens", enabled: false },
  { id: "rare_pet_only_team", label: "Rare Pet-Only Team", enabled: false },

  // Member Mode
  { id: "member_mode", label: "Full Member Mode (Treasure Track + Features)", enabled: false },
  { id: "infinite_magi_coin", label: "Infinite Magi Coin", enabled: false }
];
